### ISSUE TITLE
Can't install; "build" folder not being created?

### ISSUE THREAD

**Issue by mhbates** [ironicbadger/docker-snapraid#20]
See below. Looks like the build folder doesn't actually get made at the end, or maybe it gets removed.

Removing intermediate container ca757b1aa6bb
 ---> c32ddb0022b6
Step 12/14 : RUN mkdir /build &&     cp *.deb /build/snapraid-${SNAPRAID_VERSION}.deb
 ---> Running in 857ab53693bd
Removing intermediate container 857ab53693bd
 ---> 6ebfa659b4b8
Step 13/14 : FROM scratch
 --->
Step 14/14 : COPY --from=build /build/*.deb /
 ---> aa9e7532fabc
Successfully built aa9e7532fabc
total 32
drwxrwxr-x 4 user user 4096 Jun  5 07:17 .
drwxrwxr-x 3 user user 4096 Jun  5 07:17 ..
-rwxrwxr-x 1 user user 961 Jun  5 07:17 build.sh
-rw-rw-r-- 1 user user 700 Jun  5 07:17 Dockerfile
drwxrwxr-x 8 user user 4096 Jun  5 07:17 .git
drwxrwxr-x 3 user user 4096 Jun  5 07:17 .github
-rw-rw-r-- 1 user user 6 Jun  5 07:17 .gitignore
-rw-rw-r-- 1 user user 1363 Jun  5 07:17 README.md
**ls: cannot access './build': No such file or directory**
**Error on line 34 ./build.sh: ls -la ./build**
user@server:~/tmp/docker-snapraid$ sudo dpkg -i build/snapraid-from-source.deb
dpkg: error: cannot access archive 'build/snapraid-from-source.deb': No such file or directory

**Comment by nic-kill** [comment]
I'm also having this issue as of the current commit. No ./build directory exists. Nor can i find the file mentioned at any of the locations mentioned at the end of the output.

```
======================== Installation successful ==========================

Copying files to the temporary directory...OK

Stripping ELF binaries and libraries...OK

Compressing man pages...OK

Building file list...OK

Building Debian package...OK

NOTE: The package will not be installed

Erasing temporary files...OK

Deleting temp dir...OK


**********************************************************************

 Done. The new package has been saved to

 /snapraid-12.1/snapraid_12.1-1_amd64.deb
 You can install it in your system anytime using: 

      dpkg -i snapraid_12.1-1_amd64.deb

**********************************************************************

Removing intermediate container 187a5a881028
 ---> 08287e5f275a
Successfully built 08287e5f275a

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```
The 2020 guide command and output:

`root@nickNAS:~/tmp/docker-snapraid# sudo dpkg -i build/snapraid-from-source.deb
dpkg: error: cannot access archive 'build/snapraid-from-source.deb': No such file or directory`

Trying the directory mentioned at the end of the build.sh output:

`root@nickNAS:~/tmp/docker-snapraid# sudo dpkg -i /snapraid-12.1/snapraid_12.1-1_amd64.deb
dpkg: error: cannot access archive '/snapraid-12.1/snapraid_12.1-1_amd64.deb': No such file or directory`

Trying the command written at the end of the output:

`root@nickNAS:~/tmp/docker-snapraid# sudo dpkg -i snapraid_12.1-1_amd64.deb
dpkg: error: cannot access archive 'snapraid_12.1-1_amd64.deb': No such file or directory`

**Comment by nic-kill** [comment]
#22 fixed this for me

**Comment by trewok** [comment]
experiencing the same issue, was the fix ever merged to the master branch?

**Comment by CoordSpace** [comment]
From what I can tell, the [pull request with fixes was closed](https://github.com/ironicbadger/docker-snapraid/pull/22) and a new fork has been created instead.
 
If you really need to get a snapraid build going before a new pull request is issued, the fork seems sane and is working: https://github.com/Kmagameguy/docker-snapraid

**Comment by ironicbadger** [comment]
Should be fixed now with the reverted `build.sh` script. Sorry about that.
