### ISSUE TITLE
Unable to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by lowrents** [ironicbadger/docker-snapraid#21]
Hi, 
I just got the error: `./build.sh: 4: set: Illegal option -o pipefail` while executing `./build.sh`. After removing the -o option manually the script runs. 

----
Edit:
sorry miss-submitted the comment before I was even ready writing it. 

some more information regarding my system: 
`$  cat /etc/os-release`
```
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
`uname -r`
```
5.15.0-37-generic
```
`docker --version`
```
Docker version 20.10.17, build 100c701
```
`bash --version`
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```
`fish --version`
```
fish, version 3.3.1
```
Since the build.sh is using bash I didn't think that fish is affecting this.

Also I ran into some issues running this as part of an Ansible Playbook. I realised the out commented line too late... 

I am aware that this might not be an issued which is addressed on your side since it is not caused by your docker build in general, but it makes your script fail at the moment. It also might be possible that this is completely on my side. But as far as I can tell it is a fresh ubuntu install. The Snapraid Docker is part of an Ansible setup script. 

cheers

**Comment by Kmagameguy** [comment]
@lowrents what happens if you explicitly test bash?

Example, get the version:
`/bin/bash --version`

Or try invoking the script explicitly:
`/bin/bash build.sh`

I'm also on 22.04 but I'm not seeing issues with the `pipefail -o` option (though I'm not using fish shell).  Could be that some symlinks are out of whack or that the system is falling back to fish or just sh instead of bash for some reason 🤷🏼

**Comment by lowrents** [comment]
Hi @Kmagameguy, 
thanks for taking time to respond. Actually `/bin/bash build.sh` did the job - thank you very much. 

Actually I thought that the shebang in the first line of `build.sh` defines the shell to use, so no need to invoke the script explicitly in bash. 
On the other hand I also tested fish explicitly (`/bin/fish build.sh`) which throws me an error regarding the syntax of variable definition.

with `bash`:
```
$ /bin/bash build.sh
BUILD_ARGS=--build-arg SNAPRAID_VERSION=12.1
Sending build context to Docker daemon    107kB
Step 1/5 : FROM debian
 ---> 4eacea30377a
Step 2/5 : MAINTAINER Alex Kretzschmar <alexktz@gmail.com>
 ---> Using cache
 ---> ddccef151658
Step 3/5 : ARG SNAPRAID_VERSION
[...]
```

with `fish`:
```
$ /bin/fish build.sh
build.sh (line 19): Unsupported use of '='. In fish, please use 'set APP_NAME "snapraid"'.
warning: Error while reading file build.sh
```

without:
```
$ ./build.sh
./build.sh: 4: set: Illegal option -o pipefail
```

with `sh`:
```
$ /bin/sh build.sh
build.sh: 4: set: Illegal option -o pipefail
```

I think we found the problem, thanks for your ideas. I am still ab bit confused, but this might be due to misconception of the shebang. 

Thanks again! cheers
