### ISSUE TITLE
Scrub takes an hour to finish

### ISSUE THREAD

**Issue by kevindd992002** [IronicBadger/docker-snapraid#8]
So I have Snapraid configured like how you described it to be in your Perfect Media Server 2017 guide. It's running beautifully but starting two days ago, this are the details in the notification email I receive:

> SnapRAID job completed successfully:
> 
> 
> 2019-05-16 08:00:01,552 [INFO  ] ============================================================
> 2019-05-16 08:00:01,553 [INFO  ] Run started
> 2019-05-16 08:00:01,553 [INFO  ] ============================================================
> 2019-05-16 08:00:01,553 [INFO  ] Running diff...
> 2019-05-16 08:00:04,361 [INFO  ] ************************************************************
> 2019-05-16 08:00:04,362 [INFO  ] Diff results: 0 added,  0 removed,  0 moved,  0 modified
> 2019-05-16 08:00:04,362 [INFO  ] No changes detected, no sync required
> 2019-05-16 08:00:04,363 [INFO  ] Running scrub...
> 2019-05-16 08:59:28,816 [INFO  ] ************************************************************
> 2019-05-16 08:59:28,817 [INFO  ] All done

Why is it taking 1 hour for the scrub to happen? 3 days ago, it's been running and finishing for just under a minute (just a few seconds actually). I restarted the Debian system now and force ran the snapraid.py file using python and I'm back to how it was before this issue.

What logs can I provide to check what went wrong in the first place?

**Comment by IronicBadger** [comment]
Scrubs work out what percentage need scrubbing and only do it if required. Maybe you just started reaching the threshold. 

This isn't really the right place for this question though. May I suggest going to snapraid directly?
