### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by wesmannmsu** [IronicBadger/docker-snapraid#9]
Any hope of updating this to Buster?

**Comment by kevindd992002** [comment]
It's working for Buster just fine. I'm using it now for Buster.

**Comment by IronicBadger** [comment]
I just updated the Dockerfile to buster.

**Comment by kevindd992002** [comment]
Does that mean I have to reinstall it or something? It has been working fine for Buster for a while now.

**Comment by IronicBadger** [comment]
If you want snapraid 11.5 then you'll want to build the new package and install that. But if you're happy on 11.3 then do nothing! :)

**Comment by kevindd992002** [comment]
Right but what does updating the Dockerfile to Buster really mean regardless of the snapraid version?

**Comment by kevindd992002** [comment]
If I understand it correctly, it'a simply an update to the underlying OS of the container itself that builds the package, correct?

**Comment by IronicBadger** [comment]
Correct. The .deb file seems to be compatible with both Ubuntu and Debian systems. I'm honestly not super clear on whether I should build an Ubuntu destined .deb in Ubuntu or not, but this script works for Ubuntu 20.04 so... *shrug*.

Going to close this issue now. Thanks!
